# Jekyll configuration
name: Le blog d'iroco 
title: Le blog d'iroco 
email: hello@iroco.co
description: Blog sur l'Ã©coconception logicielle

timezone: Europe/Paris

# url is currently only used only for the RSS feed in feed.xml
url: https://blog.iroco.co

baseurl: "" # the subpath of your site
twitter_username: iroco
github_username:  iroco-co
github: 'iroco-co/iroco.github.io'

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude: ['README.md', 'LICENSE', '*.sh', '.circleci']
encoding: utf-8
